api_users_create:
  path: /api/users
  methods: POST
  controller: App\Controller\UsersController::create

api_users_pick_all:
  path: /api/users
  methods: GET
  controller: App\Controller\UsersController::pickAll

api_users_pick:
  path: /api/users/{userID}
  methods: GET
  requirements: 
    userID: '[0-9]+'
  controller: App\Controller\UsersController::pick

api_users_update:
  path: /api/users/{userID}
  methods: PATCH|PUT
  requirements:
    userID: '[0-9]+'
  controller: App\Controller\UsersController::update

api_users_delete:
  path: /api/users/{userID}
  methods: DELETE
  requirements:
    userID: '[0-9]+'
  controller: App\Controller\UsersController::delete


api_posts_create:
  path: /api/users/{userID}/posts
  methods: POST
  requirements: 
    userID: '[0-9]+'
  controller: App\Controller\PostsController::create

api_posts_pick_all:
  path: /api/posts
  methods: GET
  controller: App\Controller\PostsController::pickAll

api_posts_pick:
  path: /api/posts/{postID}
  methods: GET
  requirements:
    postID: '[0-9]+'
  controller: App\Controller\PostsController::pick